### ISSUE TITLE
N-masking human genome

### ISSUE THREAD

**Issue by parichitran** [FelixKrueger/SNPsplit#62]
Dear Felix,
I want to N-mask my Grch-38 reference genome at heterozygous SNP position

I have a VCF file generated from Whole Genome Sequencing of my cell line data with GATK-4.

But SNP split N-masks my homozygous SNPs from my VCF file.

will it be fine regarding my case

**Comment by FelixKrueger** [comment]
Hi @parichitran 

If you wanted to use SNPsplit for the the human genome you would indeed have to modify the genome preparation script to mask heterozygous positions instead of homozygous calls.

I have never used it myself yet, but alternative (and probably very useful approach) could be haplotype phasing your SNPs: https://whatshap.readthedocs.io/en/latest/

**Comment by parichitran** [comment]
Thanks a lot for your speedy reply Felix.I got cleared now.
