### ISSUE TITLE
Why I can't split bisulfite data ?

### ISSUE THREAD

**Issue by chaoyang666** [FelixKrueger/SNPsplit#64]
Hi:

I have a problem. Could you please help me with this? I can't split my bam file with SNPsplit and can't find the reasons.

My run code is as below:
SNPsplit --bisulfite --snp_file B73_V4.snp.SNP my.bam

input file1  B73_V4.snp.SNP
1       Chr10   92742   1       G/C
2       Chr10   92778   1       A/C
3       Chr10   92928   1       T/A
4       Chr10   92939   1       A/T
5       Chr10   92942   1       A/G
6       Chr10   92975   1       T/G
7       Chr10   92986   1       T/A
8       Chr10   93130   1       A/T
9       Chr10   93213   1       T/C
10      Chr10   93224   1       C/T
input file2 my.bam
![image](https://user-images.githubusercontent.com/72967806/178774545-6d08063c-1123-4ae2-a972-0bb28b411613.png)

####££££££££££££££££
OUTPUT：
Allele-tagging report
=====================
Processed 158277819 read alignments in total
Reads were unaligned and hence skipped: 0 (0.00%)
158277819 reads were unassignable (100.00%)
0 reads were specific for genome 1 (0.00%)
0 reads were specific for genome 2 (0.00%)
0 reads that were unassignable contained C>T SNPs preventing the assignment
1528 reads did not contain one of the expected bases at known SNP positions (0.00%)
0 contained conflicting allele-specific SNPs (0.00%)

Many thanks,
Chao
13/07/2022

**Comment by FelixKrueger** [comment]
The most important question for this is: did you construct, index and align an N-masked genome (e.g. with `SNPspligenome_preparation_`) for before running the bisulfite alignments. From looking at the `MD:Z:` string I can't see any mismatches to `N`s, that's why I'm asking.

A bit further up in the SNPsplit report you should also see the stat about how many reads contained mismatches to Ns. If that is 0 it would also tell you whether that was the reason...

**Comment by chaoyang666** [comment]
Dear Felix,

So far, I have solved this problem by modifying the code of  SNPsplit-0.3.4/SNPsplit_genome_preparation
`
#@chroms = (1..22,'X','Y','MT'); # this is currently using chromosomes for the human genome
    @chroms = ('Chr1','Chr2','Chr3','Chr4','Chr5','Chr6','Chr7','Chr8','Chr9','Chr10');
`
Thanks a lot,
Chao
